### ISSUE TITLE
MIS: Improving Navigation with Hyperlinks

### ISSUE THREAD

**Issue by tanya-jp** [adrian-soch/attitude_check#61] opened 2024-03-30 00:59 UTC
In Section 9.4.1, you refer to other sections of the document. Adding hyperlinks to these references would greatly improve readability and make navigation through the document much easier.

**Comment by adrian-soch** [comment] 2024-04-06 20:16
Duplicate of #65

**Closed by adrian-soch** 2024-04-06 20:16 UTC
Labels: documentation
